name: ci-cd pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mock-ekyc-api .

      - name: Mock Security Scan
        run: echo "Running TrivyScan"

      - name: Login to Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: docker tag mock-ekyc-api ${{ secrets.DOCKER_USERNAME }}/mock-ekyc-api:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mock-ekyc-api:latest

      - name: Deploy to kubernetes
        run: echo "Mock deployment to startup-namespace completed successfully"